import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'




export default function Home({newsResults,randomUsersResults}) {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen max-w-7xl mx-auto">

     {/* Sidebar */}
     <Sidebar/>




     {/* Feed */}
     <Feed/>



     {/* Widgets */}
     <Widgets newsResults={newsResults.articles} randomUsersResults={randomUsersResults.results}/>



     {/* Modal */}

      </main>
    </>
  )
}

export async function getServerSideProps(){
    const newsResults = await fetch ("https://saurav.tech/NewsAPI/top-headlines/category/business/in.json")
    .then((res)=>res.json());

    // whom to follow
   let randomUsersResults = [];
   
   try{
    const res = await fetch(
      "https://randomuser.me/api/?results=50&inc=name,login,picture"
    );

    randomUsersResults= await res.json()

   }catch(e) {
    randomUsersResults = []
   }

    return{
      props:{
       newsResults,
       randomUsersResults,
      },
    }
}

