import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'




export default function Home({newsResults}) {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen max-w-7xl mx-auto">

     {/* Sidebar */}
     <Sidebar/>




     {/* Feed */}
     <Feed/>



     {/* Widgets */}
     <Widgets newsResults={newsResults.articles}/>



     {/* Modal */}

      </main>
    </>
  )
}

export async function getServerSideProps(){
    const newsResults = await fetch ("https://saurav.tech/NewsAPI/top-headlines/category/business/in.json")
    .then((res)=>res.json());
    return{
      props:{
       newsResults,
      },
    }
}

